version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3307:3306
    volumes:
      - financial_control_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=financial_control
      - MYSQL_USER=python
      - MYSQL_PASSWORD=python

volumes:
  financial_control_data: