"""create entries table

Revision ID: e24b86f280c5
Revises: 6e87fff6a760
Create Date: 2023-07-18 19:24:37.117252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24b86f280c5'
down_revision = '6e87fff6a760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.Enum('expense', 'income', name='entrytypes'), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False, comment='Title of the entry'),
        sa.Column('amount', sa.Double(), nullable=False),
        sa.Column('installments', sa.Integer(), nullable=True, comment='Number of installments'),
        sa.Column('total_installments', sa.Integer(), nullable=True, comment='Total number of installments'),
        sa.Column('due_date', sa.Date(), nullable=True),
        sa.Column('payday', sa.Date(), nullable=True),
        sa.Column('is_recurring', sa.Boolean(), nullable=True, comment='If recurring is expense'),
        sa.Column('start_date', sa.Date(), nullable=True, comment='Expense start date and/or revenue reference'),
        sa.Column('sequence', sa.Integer(), nullable=True, comment='Grouping of recurring installments'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deletead_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    # ### end Alembic commands ###
